// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: pg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*Query `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (x *MultiQuery) Reset() {
	*x = MultiQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiQuery) ProtoMessage() {}

func (x *MultiQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiQuery.ProtoReflect.Descriptor instead.
func (*MultiQuery) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{0}
}

func (x *MultiQuery) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

type MultiQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*QueryResp `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *MultiQueryResp) Reset() {
	*x = MultiQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiQueryResp) ProtoMessage() {}

func (x *MultiQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiQueryResp.ProtoReflect.Descriptor instead.
func (*MultiQueryResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{1}
}

func (x *MultiQueryResp) GetResults() []*QueryResp {
	if x != nil {
		return x.Results
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryId *int32       `protobuf:"varint,1,req,name=query_id,json=queryId" json:"query_id,omitempty"`
	Queries []*QueryInfo `protobuf:"bytes,2,rep,name=queries" json:"queries,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetQueryId() int32 {
	if x != nil && x.QueryId != nil {
		return *x.QueryId
	}
	return 0
}

func (x *Query) GetQueries() []*QueryInfo {
	if x != nil {
		return x.Queries
	}
	return nil
}

type QueryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    []string `protobuf:"bytes,1,rep,name=from" json:"from,omitempty"`
	OrderBy []string `protobuf:"bytes,2,rep,name=order_by,json=orderBy" json:"order_by,omitempty"`
	Limit   *int32   `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Column  []string `protobuf:"bytes,4,rep,name=column" json:"column,omitempty"`
	Where   *string  `protobuf:"bytes,5,opt,name=where" json:"where,omitempty"`
}

func (x *QueryInfo) Reset() {
	*x = QueryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInfo) ProtoMessage() {}

func (x *QueryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInfo.ProtoReflect.Descriptor instead.
func (*QueryInfo) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{3}
}

func (x *QueryInfo) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *QueryInfo) GetOrderBy() []string {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *QueryInfo) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryInfo) GetColumn() []string {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *QueryInfo) GetWhere() string {
	if x != nil && x.Where != nil {
		return *x.Where
	}
	return ""
}

type QueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*QueryResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *QueryResp) Reset() {
	*x = QueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResp) ProtoMessage() {}

func (x *QueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResp.ProtoReflect.Descriptor instead.
func (*QueryResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResp) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

//This array is a matrix - if a query returns 10 columns and 5 rows, it will have len of 50.
//[0:10] would be the first row, [11:20] the second row, etc.
type QueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column []string `protobuf:"bytes,1,rep,name=column" json:"column,omitempty"`
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResult) GetColumn() []string {
	if x != nil {
		return x.Column
	}
	return nil
}

type BulkInsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regions   []*InsertRegion   `protobuf:"bytes,1,rep,name=regions" json:"regions,omitempty"`
	Nations   []*InsertNation   `protobuf:"bytes,2,rep,name=nations" json:"nations,omitempty"`
	Parts     []*InsertPart     `protobuf:"bytes,3,rep,name=parts" json:"parts,omitempty"`
	Suppliers []*InsertSupplier `protobuf:"bytes,4,rep,name=suppliers" json:"suppliers,omitempty"`
	PartSupps []*InsertPartSupp `protobuf:"bytes,5,rep,name=partSupps" json:"partSupps,omitempty"`
	Customers []*InsertCustomer `protobuf:"bytes,6,rep,name=customers" json:"customers,omitempty"`
	Orders    []*InsertOrder    `protobuf:"bytes,7,rep,name=orders" json:"orders,omitempty"`
	LineItems []*InsertLineItem `protobuf:"bytes,8,rep,name=lineItems" json:"lineItems,omitempty"`
	Arbitrary []*Insert         `protobuf:"bytes,9,rep,name=arbitrary" json:"arbitrary,omitempty"`
}

func (x *BulkInsert) Reset() {
	*x = BulkInsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkInsert) ProtoMessage() {}

func (x *BulkInsert) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkInsert.ProtoReflect.Descriptor instead.
func (*BulkInsert) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{6}
}

func (x *BulkInsert) GetRegions() []*InsertRegion {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *BulkInsert) GetNations() []*InsertNation {
	if x != nil {
		return x.Nations
	}
	return nil
}

func (x *BulkInsert) GetParts() []*InsertPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *BulkInsert) GetSuppliers() []*InsertSupplier {
	if x != nil {
		return x.Suppliers
	}
	return nil
}

func (x *BulkInsert) GetPartSupps() []*InsertPartSupp {
	if x != nil {
		return x.PartSupps
	}
	return nil
}

func (x *BulkInsert) GetCustomers() []*InsertCustomer {
	if x != nil {
		return x.Customers
	}
	return nil
}

func (x *BulkInsert) GetOrders() []*InsertOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *BulkInsert) GetLineItems() []*InsertLineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *BulkInsert) GetArbitrary() []*Insert {
	if x != nil {
		return x.Arbitrary
	}
	return nil
}

type MultiTpchUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders      []*InsertOrder    `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
	Items       []*InsertLineItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	DeleteTable *string           `protobuf:"bytes,3,opt,name=deleteTable" json:"deleteTable,omitempty"`
	DeleteIds   []string          `protobuf:"bytes,4,rep,name=deleteIds" json:"deleteIds,omitempty"`
}

func (x *MultiTpchUpdate) Reset() {
	*x = MultiTpchUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiTpchUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTpchUpdate) ProtoMessage() {}

func (x *MultiTpchUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTpchUpdate.ProtoReflect.Descriptor instead.
func (*MultiTpchUpdate) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{7}
}

func (x *MultiTpchUpdate) GetOrders() []*InsertOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *MultiTpchUpdate) GetItems() []*InsertLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MultiTpchUpdate) GetDeleteTable() string {
	if x != nil && x.DeleteTable != nil {
		return *x.DeleteTable
	}
	return ""
}

func (x *MultiTpchUpdate) GetDeleteIds() []string {
	if x != nil {
		return x.DeleteIds
	}
	return nil
}

type MultiTpchUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MultiTpchUpdateResp) Reset() {
	*x = MultiTpchUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiTpchUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTpchUpdateResp) ProtoMessage() {}

func (x *MultiTpchUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTpchUpdateResp.ProtoReflect.Descriptor instead.
func (*MultiTpchUpdateResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{8}
}

type TpchUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Insert *InsertOrderItems `protobuf:"bytes,1,req,name=insert" json:"insert,omitempty"`
	Delete *Delete           `protobuf:"bytes,2,req,name=delete" json:"delete,omitempty"`
}

func (x *TpchUpdate) Reset() {
	*x = TpchUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TpchUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpchUpdate) ProtoMessage() {}

func (x *TpchUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpchUpdate.ProtoReflect.Descriptor instead.
func (*TpchUpdate) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{9}
}

func (x *TpchUpdate) GetInsert() *InsertOrderItems {
	if x != nil {
		return x.Insert
	}
	return nil
}

func (x *TpchUpdate) GetDelete() *Delete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type TpchUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TpchUpdateResp) Reset() {
	*x = TpchUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TpchUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpchUpdateResp) ProtoMessage() {}

func (x *TpchUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpchUpdateResp.ProtoReflect.Descriptor instead.
func (*TpchUpdateResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{10}
}

type InsertOrderItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order     *InsertOrder      `protobuf:"bytes,1,req,name=order" json:"order,omitempty"`
	LineItems []*InsertLineItem `protobuf:"bytes,2,rep,name=lineItems" json:"lineItems,omitempty"`
}

func (x *InsertOrderItems) Reset() {
	*x = InsertOrderItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertOrderItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOrderItems) ProtoMessage() {}

func (x *InsertOrderItems) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOrderItems.ProtoReflect.Descriptor instead.
func (*InsertOrderItems) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{11}
}

func (x *InsertOrderItems) GetOrder() *InsertOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *InsertOrderItems) GetLineItems() []*InsertLineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

type Insert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns []string `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	Table   *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
}

func (x *Insert) Reset() {
	*x = Insert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insert) ProtoMessage() {}

func (x *Insert) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insert.ProtoReflect.Descriptor instead.
func (*Insert) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{12}
}

func (x *Insert) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Insert) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

type InsertResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InsertResp) Reset() {
	*x = InsertResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResp) ProtoMessage() {}

func (x *InsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResp.ProtoReflect.Descriptor instead.
func (*InsertResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{13}
}

type InsertRegion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionKey *int32  `protobuf:"varint,1,req,name=regionKey" json:"regionKey,omitempty"`
	Name      *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Comment   *string `protobuf:"bytes,3,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertRegion) Reset() {
	*x = InsertRegion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRegion) ProtoMessage() {}

func (x *InsertRegion) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRegion.ProtoReflect.Descriptor instead.
func (*InsertRegion) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{14}
}

func (x *InsertRegion) GetRegionKey() int32 {
	if x != nil && x.RegionKey != nil {
		return *x.RegionKey
	}
	return 0
}

func (x *InsertRegion) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InsertRegion) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InsertNation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NationKey *int32  `protobuf:"varint,1,req,name=nationKey" json:"nationKey,omitempty"`
	Name      *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	RegionKey *int32  `protobuf:"varint,3,req,name=regionKey" json:"regionKey,omitempty"`
	Comment   *string `protobuf:"bytes,4,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertNation) Reset() {
	*x = InsertNation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertNation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertNation) ProtoMessage() {}

func (x *InsertNation) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertNation.ProtoReflect.Descriptor instead.
func (*InsertNation) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{15}
}

func (x *InsertNation) GetNationKey() int32 {
	if x != nil && x.NationKey != nil {
		return *x.NationKey
	}
	return 0
}

func (x *InsertNation) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InsertNation) GetRegionKey() int32 {
	if x != nil && x.RegionKey != nil {
		return *x.RegionKey
	}
	return 0
}

func (x *InsertNation) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InsertPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartKey     *int32  `protobuf:"varint,1,req,name=partKey" json:"partKey,omitempty"`
	Name        *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Mfgr        *string `protobuf:"bytes,3,req,name=mfgr" json:"mfgr,omitempty"`
	Brand       *string `protobuf:"bytes,4,req,name=brand" json:"brand,omitempty"`
	Type        *string `protobuf:"bytes,5,req,name=type" json:"type,omitempty"`
	Size        *string `protobuf:"bytes,6,req,name=size" json:"size,omitempty"`
	Container   *string `protobuf:"bytes,7,req,name=container" json:"container,omitempty"`
	RetailPrice *string `protobuf:"bytes,8,req,name=retailPrice" json:"retailPrice,omitempty"`
	Comment     *string `protobuf:"bytes,9,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertPart) Reset() {
	*x = InsertPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPart) ProtoMessage() {}

func (x *InsertPart) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPart.ProtoReflect.Descriptor instead.
func (*InsertPart) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{16}
}

func (x *InsertPart) GetPartKey() int32 {
	if x != nil && x.PartKey != nil {
		return *x.PartKey
	}
	return 0
}

func (x *InsertPart) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InsertPart) GetMfgr() string {
	if x != nil && x.Mfgr != nil {
		return *x.Mfgr
	}
	return ""
}

func (x *InsertPart) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

func (x *InsertPart) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *InsertPart) GetSize() string {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return ""
}

func (x *InsertPart) GetContainer() string {
	if x != nil && x.Container != nil {
		return *x.Container
	}
	return ""
}

func (x *InsertPart) GetRetailPrice() string {
	if x != nil && x.RetailPrice != nil {
		return *x.RetailPrice
	}
	return ""
}

func (x *InsertPart) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InsertSupplier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuppKey   *int32  `protobuf:"varint,1,req,name=suppKey" json:"suppKey,omitempty"`
	Name      *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Address   *string `protobuf:"bytes,3,req,name=address" json:"address,omitempty"`
	NationKey *int32  `protobuf:"varint,4,req,name=nationKey" json:"nationKey,omitempty"`
	Phone     *string `protobuf:"bytes,5,req,name=phone" json:"phone,omitempty"`
	AcctBal   *string `protobuf:"bytes,6,req,name=acctBal" json:"acctBal,omitempty"`
	Comment   *string `protobuf:"bytes,7,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertSupplier) Reset() {
	*x = InsertSupplier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertSupplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSupplier) ProtoMessage() {}

func (x *InsertSupplier) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSupplier.ProtoReflect.Descriptor instead.
func (*InsertSupplier) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{17}
}

func (x *InsertSupplier) GetSuppKey() int32 {
	if x != nil && x.SuppKey != nil {
		return *x.SuppKey
	}
	return 0
}

func (x *InsertSupplier) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InsertSupplier) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *InsertSupplier) GetNationKey() int32 {
	if x != nil && x.NationKey != nil {
		return *x.NationKey
	}
	return 0
}

func (x *InsertSupplier) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *InsertSupplier) GetAcctBal() string {
	if x != nil && x.AcctBal != nil {
		return *x.AcctBal
	}
	return ""
}

func (x *InsertSupplier) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InsertPartSupp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartKey    *int32   `protobuf:"varint,1,req,name=partKey" json:"partKey,omitempty"`
	SuppKey    *int32   `protobuf:"varint,2,req,name=suppKey" json:"suppKey,omitempty"`
	AvailQty   *int32   `protobuf:"varint,3,req,name=availQty" json:"availQty,omitempty"`
	SupplyCost *float64 `protobuf:"fixed64,4,req,name=supplyCost" json:"supplyCost,omitempty"`
	Comment    *string  `protobuf:"bytes,5,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertPartSupp) Reset() {
	*x = InsertPartSupp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPartSupp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPartSupp) ProtoMessage() {}

func (x *InsertPartSupp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPartSupp.ProtoReflect.Descriptor instead.
func (*InsertPartSupp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{18}
}

func (x *InsertPartSupp) GetPartKey() int32 {
	if x != nil && x.PartKey != nil {
		return *x.PartKey
	}
	return 0
}

func (x *InsertPartSupp) GetSuppKey() int32 {
	if x != nil && x.SuppKey != nil {
		return *x.SuppKey
	}
	return 0
}

func (x *InsertPartSupp) GetAvailQty() int32 {
	if x != nil && x.AvailQty != nil {
		return *x.AvailQty
	}
	return 0
}

func (x *InsertPartSupp) GetSupplyCost() float64 {
	if x != nil && x.SupplyCost != nil {
		return *x.SupplyCost
	}
	return 0
}

func (x *InsertPartSupp) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InsertCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustKey    *int32  `protobuf:"varint,1,req,name=custKey" json:"custKey,omitempty"`
	Name       *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Address    *string `protobuf:"bytes,3,req,name=address" json:"address,omitempty"`
	NationKey  *int32  `protobuf:"varint,4,req,name=nationKey" json:"nationKey,omitempty"`
	Phone      *string `protobuf:"bytes,5,req,name=phone" json:"phone,omitempty"`
	AcctBal    *string `protobuf:"bytes,6,req,name=acctBal" json:"acctBal,omitempty"`
	MktSegment *string `protobuf:"bytes,7,req,name=mktSegment" json:"mktSegment,omitempty"`
	Comment    *string `protobuf:"bytes,8,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertCustomer) Reset() {
	*x = InsertCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCustomer) ProtoMessage() {}

func (x *InsertCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCustomer.ProtoReflect.Descriptor instead.
func (*InsertCustomer) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{19}
}

func (x *InsertCustomer) GetCustKey() int32 {
	if x != nil && x.CustKey != nil {
		return *x.CustKey
	}
	return 0
}

func (x *InsertCustomer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InsertCustomer) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *InsertCustomer) GetNationKey() int32 {
	if x != nil && x.NationKey != nil {
		return *x.NationKey
	}
	return 0
}

func (x *InsertCustomer) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *InsertCustomer) GetAcctBal() string {
	if x != nil && x.AcctBal != nil {
		return *x.AcctBal
	}
	return ""
}

func (x *InsertCustomer) GetMktSegment() string {
	if x != nil && x.MktSegment != nil {
		return *x.MktSegment
	}
	return ""
}

func (x *InsertCustomer) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InsertOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderKey      *int32  `protobuf:"varint,1,req,name=orderKey" json:"orderKey,omitempty"`
	CustKey       *int32  `protobuf:"varint,2,req,name=custKey" json:"custKey,omitempty"`
	OrderStatus   *string `protobuf:"bytes,3,req,name=orderStatus" json:"orderStatus,omitempty"`
	TotalPrice    *string `protobuf:"bytes,4,req,name=totalPrice" json:"totalPrice,omitempty"`
	OrderDate     *Date   `protobuf:"bytes,5,req,name=orderDate" json:"orderDate,omitempty"`
	OrderPriority *string `protobuf:"bytes,6,req,name=orderPriority" json:"orderPriority,omitempty"`
	Clerk         *string `protobuf:"bytes,7,req,name=clerk" json:"clerk,omitempty"`
	ShipPriority  *string `protobuf:"bytes,8,req,name=shipPriority" json:"shipPriority,omitempty"`
	Comment       *string `protobuf:"bytes,9,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertOrder) Reset() {
	*x = InsertOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOrder) ProtoMessage() {}

func (x *InsertOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOrder.ProtoReflect.Descriptor instead.
func (*InsertOrder) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{20}
}

func (x *InsertOrder) GetOrderKey() int32 {
	if x != nil && x.OrderKey != nil {
		return *x.OrderKey
	}
	return 0
}

func (x *InsertOrder) GetCustKey() int32 {
	if x != nil && x.CustKey != nil {
		return *x.CustKey
	}
	return 0
}

func (x *InsertOrder) GetOrderStatus() string {
	if x != nil && x.OrderStatus != nil {
		return *x.OrderStatus
	}
	return ""
}

func (x *InsertOrder) GetTotalPrice() string {
	if x != nil && x.TotalPrice != nil {
		return *x.TotalPrice
	}
	return ""
}

func (x *InsertOrder) GetOrderDate() *Date {
	if x != nil {
		return x.OrderDate
	}
	return nil
}

func (x *InsertOrder) GetOrderPriority() string {
	if x != nil && x.OrderPriority != nil {
		return *x.OrderPriority
	}
	return ""
}

func (x *InsertOrder) GetClerk() string {
	if x != nil && x.Clerk != nil {
		return *x.Clerk
	}
	return ""
}

func (x *InsertOrder) GetShipPriority() string {
	if x != nil && x.ShipPriority != nil {
		return *x.ShipPriority
	}
	return ""
}

func (x *InsertOrder) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InsertLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderKey      *int32   `protobuf:"varint,1,req,name=orderKey" json:"orderKey,omitempty"`
	PartKey       *int32   `protobuf:"varint,2,req,name=partKey" json:"partKey,omitempty"`
	SuppKey       *int32   `protobuf:"varint,3,req,name=suppKey" json:"suppKey,omitempty"`
	LineNumber    *int32   `protobuf:"varint,4,req,name=lineNumber" json:"lineNumber,omitempty"`
	Quantity      *int32   `protobuf:"varint,5,req,name=quantity" json:"quantity,omitempty"`
	ExtendedPrice *float64 `protobuf:"fixed64,6,req,name=extendedPrice" json:"extendedPrice,omitempty"`
	Discount      *float64 `protobuf:"fixed64,7,req,name=discount" json:"discount,omitempty"`
	Tax           *float64 `protobuf:"fixed64,8,req,name=tax" json:"tax,omitempty"`
	ReturnFlag    *string  `protobuf:"bytes,9,req,name=returnFlag" json:"returnFlag,omitempty"`
	LineStatus    *string  `protobuf:"bytes,10,req,name=lineStatus" json:"lineStatus,omitempty"`
	ShipDate      *Date    `protobuf:"bytes,11,req,name=shipDate" json:"shipDate,omitempty"`
	CommitDate    *Date    `protobuf:"bytes,12,req,name=commitDate" json:"commitDate,omitempty"`
	ReceiptDate   *Date    `protobuf:"bytes,13,req,name=receiptDate" json:"receiptDate,omitempty"`
	ShipInstruct  *string  `protobuf:"bytes,14,req,name=shipInstruct" json:"shipInstruct,omitempty"`
	ShipMode      *string  `protobuf:"bytes,15,req,name=shipMode" json:"shipMode,omitempty"`
	Comment       *string  `protobuf:"bytes,16,req,name=comment" json:"comment,omitempty"`
}

func (x *InsertLineItem) Reset() {
	*x = InsertLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLineItem) ProtoMessage() {}

func (x *InsertLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLineItem.ProtoReflect.Descriptor instead.
func (*InsertLineItem) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{21}
}

func (x *InsertLineItem) GetOrderKey() int32 {
	if x != nil && x.OrderKey != nil {
		return *x.OrderKey
	}
	return 0
}

func (x *InsertLineItem) GetPartKey() int32 {
	if x != nil && x.PartKey != nil {
		return *x.PartKey
	}
	return 0
}

func (x *InsertLineItem) GetSuppKey() int32 {
	if x != nil && x.SuppKey != nil {
		return *x.SuppKey
	}
	return 0
}

func (x *InsertLineItem) GetLineNumber() int32 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

func (x *InsertLineItem) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *InsertLineItem) GetExtendedPrice() float64 {
	if x != nil && x.ExtendedPrice != nil {
		return *x.ExtendedPrice
	}
	return 0
}

func (x *InsertLineItem) GetDiscount() float64 {
	if x != nil && x.Discount != nil {
		return *x.Discount
	}
	return 0
}

func (x *InsertLineItem) GetTax() float64 {
	if x != nil && x.Tax != nil {
		return *x.Tax
	}
	return 0
}

func (x *InsertLineItem) GetReturnFlag() string {
	if x != nil && x.ReturnFlag != nil {
		return *x.ReturnFlag
	}
	return ""
}

func (x *InsertLineItem) GetLineStatus() string {
	if x != nil && x.LineStatus != nil {
		return *x.LineStatus
	}
	return ""
}

func (x *InsertLineItem) GetShipDate() *Date {
	if x != nil {
		return x.ShipDate
	}
	return nil
}

func (x *InsertLineItem) GetCommitDate() *Date {
	if x != nil {
		return x.CommitDate
	}
	return nil
}

func (x *InsertLineItem) GetReceiptDate() *Date {
	if x != nil {
		return x.ReceiptDate
	}
	return nil
}

func (x *InsertLineItem) GetShipInstruct() string {
	if x != nil && x.ShipInstruct != nil {
		return *x.ShipInstruct
	}
	return ""
}

func (x *InsertLineItem) GetShipMode() string {
	if x != nil && x.ShipMode != nil {
		return *x.ShipMode
	}
	return ""
}

func (x *InsertLineItem) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table     *string `protobuf:"bytes,1,req,name=table" json:"table,omitempty"`         //From
	Condition *string `protobuf:"bytes,2,req,name=condition" json:"condition,omitempty"` //Where
}

func (x *Delete) Reset() {
	*x = Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{22}
}

func (x *Delete) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

func (x *Delete) GetCondition() string {
	if x != nil && x.Condition != nil {
		return *x.Condition
	}
	return ""
}

type DeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{23}
}

type CreateTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId     []int32       `protobuf:"varint,1,rep,name=table_id,json=tableId" json:"table_id,omitempty"`
	ForeignKeys []*ForeignKey `protobuf:"bytes,2,rep,name=foreign_keys,json=foreignKeys" json:"foreign_keys,omitempty"` //Only used with table_id. One entry per table_id, each entry can have multiple keys.
	Statement   []string      `protobuf:"bytes,3,rep,name=statement" json:"statement,omitempty"`
}

func (x *CreateTable) Reset() {
	*x = CreateTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTable) ProtoMessage() {}

func (x *CreateTable) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTable.ProtoReflect.Descriptor instead.
func (*CreateTable) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTable) GetTableId() []int32 {
	if x != nil {
		return x.TableId
	}
	return nil
}

func (x *CreateTable) GetForeignKeys() []*ForeignKey {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

func (x *CreateTable) GetStatement() []string {
	if x != nil {
		return x.Statement
	}
	return nil
}

type ForeignKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForeignKey []string `protobuf:"bytes,1,rep,name=foreign_key,json=foreignKey" json:"foreign_key,omitempty"`
}

func (x *ForeignKey) Reset() {
	*x = ForeignKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignKey) ProtoMessage() {}

func (x *ForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignKey.ProtoReflect.Descriptor instead.
func (*ForeignKey) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{25}
}

func (x *ForeignKey) GetForeignKey() []string {
	if x != nil {
		return x.ForeignKey
	}
	return nil
}

type CreateTableResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTableResp) Reset() {
	*x = CreateTableResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableResp) ProtoMessage() {}

func (x *CreateTableResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableResp.ProtoReflect.Descriptor instead.
func (*CreateTableResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{26}
}

type DropTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table []string `protobuf:"bytes,1,rep,name=table" json:"table,omitempty"`
}

func (x *DropTable) Reset() {
	*x = DropTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTable) ProtoMessage() {}

func (x *DropTable) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTable.ProtoReflect.Descriptor instead.
func (*DropTable) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{27}
}

func (x *DropTable) GetTable() []string {
	if x != nil {
		return x.Table
	}
	return nil
}

type DropTableResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropTableResp) Reset() {
	*x = DropTableResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableResp) ProtoMessage() {}

func (x *DropTableResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableResp.ProtoReflect.Descriptor instead.
func (*DropTableResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{28}
}

type CreateView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement []string `protobuf:"bytes,1,rep,name=statement" json:"statement,omitempty"`
}

func (x *CreateView) Reset() {
	*x = CreateView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateView) ProtoMessage() {}

func (x *CreateView) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateView.ProtoReflect.Descriptor instead.
func (*CreateView) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{29}
}

func (x *CreateView) GetStatement() []string {
	if x != nil {
		return x.Statement
	}
	return nil
}

type CreateViewResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg *string `protobuf:"bytes,1,opt,name=errorMsg" json:"errorMsg,omitempty"`
}

func (x *CreateViewResp) Reset() {
	*x = CreateViewResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewResp) ProtoMessage() {}

func (x *CreateViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewResp.ProtoReflect.Descriptor instead.
func (*CreateViewResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{30}
}

func (x *CreateViewResp) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

type DropView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View []string `protobuf:"bytes,1,rep,name=view" json:"view,omitempty"`
}

func (x *DropView) Reset() {
	*x = DropView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropView) ProtoMessage() {}

func (x *DropView) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropView.ProtoReflect.Descriptor instead.
func (*DropView) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{31}
}

func (x *DropView) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

type DropViewResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropViewResp) Reset() {
	*x = DropViewResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropViewResp) ProtoMessage() {}

func (x *DropViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropViewResp.ProtoReflect.Descriptor instead.
func (*DropViewResp) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{32}
}

type CloseConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseConnection) Reset() {
	*x = CloseConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnection) ProtoMessage() {}

func (x *CloseConnection) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnection.ProtoReflect.Descriptor instead.
func (*CloseConnection) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{33}
}

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  *int32 `protobuf:"varint,1,req,name=year" json:"year,omitempty"`
	Month *int32 `protobuf:"varint,2,req,name=month" json:"month,omitempty"`
	Day   *int32 `protobuf:"varint,3,req,name=day" json:"day,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_pg_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_pg_proto_rawDescGZIP(), []int{34}
}

func (x *Date) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

var File_pg_proto protoreflect.FileDescriptor

var file_pg_proto_rawDesc = []byte{
	0x0a, 0x08, 0x70, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x0a, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x0e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x48, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x7e, 0x0a, 0x09,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x22, 0x33, 0x0a, 0x09,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x22, 0x25, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x8a, 0x03, 0x0a, 0x0a, 0x42, 0x75, 0x6c,
	0x6b, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x27, 0x0a, 0x07, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x61, 0x72,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x09,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x52, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x70,
	0x61, 0x72, 0x74, 0x53, 0x75, 0x70, 0x70, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x74, 0x53, 0x75, 0x70, 0x70, 0x52,
	0x09, 0x70, 0x61, 0x72, 0x74, 0x53, 0x75, 0x70, 0x70, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x09,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x2d, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x25,
	0x0a, 0x09, 0x61, 0x72, 0x62, 0x69, 0x74, 0x72, 0x61, 0x72, 0x79, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x09, 0x61, 0x72, 0x62, 0x69,
	0x74, 0x72, 0x61, 0x72, 0x79, 0x22, 0x9e, 0x01, 0x0a, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x54,
	0x70, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x25, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x49, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x64, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x54,
	0x70, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x58, 0x0a,
	0x0a, 0x54, 0x70, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x69,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x06,
	0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x54, 0x70, 0x63, 0x68, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x65, 0x0a, 0x10, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x22, 0x0a,
	0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x2d, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x38, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x5a, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x78, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xe6,
	0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x66, 0x67, 0x72, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x66, 0x67, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x07, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xc0, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x70, 0x70, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x73, 0x75, 0x70,
	0x70, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x74, 0x42, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x74, 0x42, 0x61, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x74, 0x53, 0x75, 0x70, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x70, 0x70, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x73, 0x75, 0x70, 0x70, 0x4b, 0x65,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x51, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x08, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x51, 0x74, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x01, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xe0, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75,
	0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x74, 0x42, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x74, 0x42, 0x61, 0x6c,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6b, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x07,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6b, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xa4, 0x02, 0x0a, 0x0b, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x73, 0x74, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x73, 0x74, 0x4b, 0x65, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x23, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0d,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6c, 0x65, 0x72, 0x6b, 0x18, 0x07, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c,
	0x65, 0x72, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x68, 0x69, 0x70, 0x50, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x68, 0x69, 0x70, 0x50,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x09, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0xfd, 0x03, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x70, 0x70, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x73, 0x75, 0x70,
	0x70, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x24, 0x0a, 0x0d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x02, 0x28, 0x01, 0x52, 0x0d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65,
	0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x07, 0x20, 0x02, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x78, 0x18, 0x08, 0x20, 0x02, 0x28, 0x01, 0x52,
	0x03, 0x74, 0x61, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x46, 0x6c,
	0x61, 0x67, 0x18, 0x09, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x46, 0x6c, 0x61, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x0b, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x08, 0x73,
	0x68, 0x69, 0x70, 0x44, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x27,
	0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0d, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x68, 0x69, 0x70, 0x49,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x0e, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x68, 0x69, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x68, 0x69, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x0f, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x69, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x10, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x3c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x0c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x76, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x0c, 0x66, 0x6f, 0x72, 0x65, 0x69,
	0x67, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x0b, 0x66, 0x6f, 0x72, 0x65,
	0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e,
	0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67,
	0x6e, 0x4b, 0x65, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x09, 0x44, 0x72, 0x6f, 0x70, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x72,
	0x6f, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1e, 0x0a, 0x08, 0x44, 0x72, 0x6f, 0x70, 0x56, 0x69, 0x65,
	0x77, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x76, 0x69, 0x65, 0x77, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x72, 0x6f, 0x70, 0x56, 0x69, 0x65,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61,
	0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x42, 0x1c, 0x5a, 0x1a,
	0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x5f, 0x74, 0x70, 0x63, 0x68, 0x5f, 0x67, 0x6f,
	0x5f, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_pg_proto_rawDescOnce sync.Once
	file_pg_proto_rawDescData = file_pg_proto_rawDesc
)

func file_pg_proto_rawDescGZIP() []byte {
	file_pg_proto_rawDescOnce.Do(func() {
		file_pg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pg_proto_rawDescData)
	})
	return file_pg_proto_rawDescData
}

var file_pg_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_pg_proto_goTypes = []interface{}{
	(*MultiQuery)(nil),          // 0: MultiQuery
	(*MultiQueryResp)(nil),      // 1: MultiQueryResp
	(*Query)(nil),               // 2: Query
	(*QueryInfo)(nil),           // 3: QueryInfo
	(*QueryResp)(nil),           // 4: QueryResp
	(*QueryResult)(nil),         // 5: QueryResult
	(*BulkInsert)(nil),          // 6: BulkInsert
	(*MultiTpchUpdate)(nil),     // 7: MultiTpchUpdate
	(*MultiTpchUpdateResp)(nil), // 8: MultiTpchUpdateResp
	(*TpchUpdate)(nil),          // 9: TpchUpdate
	(*TpchUpdateResp)(nil),      // 10: TpchUpdateResp
	(*InsertOrderItems)(nil),    // 11: InsertOrderItems
	(*Insert)(nil),              // 12: Insert
	(*InsertResp)(nil),          // 13: InsertResp
	(*InsertRegion)(nil),        // 14: InsertRegion
	(*InsertNation)(nil),        // 15: InsertNation
	(*InsertPart)(nil),          // 16: InsertPart
	(*InsertSupplier)(nil),      // 17: InsertSupplier
	(*InsertPartSupp)(nil),      // 18: InsertPartSupp
	(*InsertCustomer)(nil),      // 19: InsertCustomer
	(*InsertOrder)(nil),         // 20: InsertOrder
	(*InsertLineItem)(nil),      // 21: InsertLineItem
	(*Delete)(nil),              // 22: Delete
	(*DeleteResp)(nil),          // 23: DeleteResp
	(*CreateTable)(nil),         // 24: CreateTable
	(*ForeignKey)(nil),          // 25: ForeignKey
	(*CreateTableResp)(nil),     // 26: CreateTableResp
	(*DropTable)(nil),           // 27: DropTable
	(*DropTableResp)(nil),       // 28: DropTableResp
	(*CreateView)(nil),          // 29: CreateView
	(*CreateViewResp)(nil),      // 30: CreateViewResp
	(*DropView)(nil),            // 31: DropView
	(*DropViewResp)(nil),        // 32: DropViewResp
	(*CloseConnection)(nil),     // 33: CloseConnection
	(*Date)(nil),                // 34: Date
}
var file_pg_proto_depIdxs = []int32{
	2,  // 0: MultiQuery.queries:type_name -> Query
	4,  // 1: MultiQueryResp.results:type_name -> QueryResp
	3,  // 2: Query.queries:type_name -> QueryInfo
	5,  // 3: QueryResp.results:type_name -> QueryResult
	14, // 4: BulkInsert.regions:type_name -> InsertRegion
	15, // 5: BulkInsert.nations:type_name -> InsertNation
	16, // 6: BulkInsert.parts:type_name -> InsertPart
	17, // 7: BulkInsert.suppliers:type_name -> InsertSupplier
	18, // 8: BulkInsert.partSupps:type_name -> InsertPartSupp
	19, // 9: BulkInsert.customers:type_name -> InsertCustomer
	20, // 10: BulkInsert.orders:type_name -> InsertOrder
	21, // 11: BulkInsert.lineItems:type_name -> InsertLineItem
	12, // 12: BulkInsert.arbitrary:type_name -> Insert
	20, // 13: MultiTpchUpdate.orders:type_name -> InsertOrder
	21, // 14: MultiTpchUpdate.items:type_name -> InsertLineItem
	11, // 15: TpchUpdate.insert:type_name -> InsertOrderItems
	22, // 16: TpchUpdate.delete:type_name -> Delete
	20, // 17: InsertOrderItems.order:type_name -> InsertOrder
	21, // 18: InsertOrderItems.lineItems:type_name -> InsertLineItem
	34, // 19: InsertOrder.orderDate:type_name -> Date
	34, // 20: InsertLineItem.shipDate:type_name -> Date
	34, // 21: InsertLineItem.commitDate:type_name -> Date
	34, // 22: InsertLineItem.receiptDate:type_name -> Date
	25, // 23: CreateTable.foreign_keys:type_name -> ForeignKey
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pg_proto_init() }
func file_pg_proto_init() {
	if File_pg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkInsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiTpchUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiTpchUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TpchUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TpchUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertOrderItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Insert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertRegion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertNation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertSupplier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPartSupp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForeignKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTableResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTableResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateViewResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropViewResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pg_proto_goTypes,
		DependencyIndexes: file_pg_proto_depIdxs,
		MessageInfos:      file_pg_proto_msgTypes,
	}.Build()
	File_pg_proto = out.File
	file_pg_proto_rawDesc = nil
	file_pg_proto_goTypes = nil
	file_pg_proto_depIdxs = nil
}
